# BANK DATASET ANALYSIS


In [5]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from scipy import stats
stats.chisqprob = lambda chisq, df: stats.chi2.sf(chisq, df)

In [8]:
data=pd.read_csv("C:\\Users\\anish\\Documents\\DATA_SCIENCE_JUPYTER\\Logistic Regression\\bank_data.csv")

data.head()

Unnamed: 0  interest_rate  credit  march  may  previous  duration    y
0           0          1.334     0.0    1.0  0.0       0.0     117.0   no
1           1          0.767     0.0    0.0  2.0       1.0     274.0  yes
2           2          4.858     0.0    1.0  0.0       0.0     167.0   no
3           3          4.120     0.0    0.0  0.0       0.0     686.0  yes
4           4          4.856     0.0    1.0  0.0       0.0     157.0   no

In [9]:
data=data.drop(['Unnamed: 0'],axis=1)
data.head()

interest_rate  credit  march  may  previous  duration    y
0          1.334     0.0    1.0  0.0       0.0     117.0   no
1          0.767     0.0    0.0  2.0       1.0     274.0  yes
2          4.858     0.0    1.0  0.0       0.0     167.0   no
3          4.120     0.0    0.0  0.0       0.0     686.0  yes
4          4.856     0.0    1.0  0.0       0.0     157.0   no

In [10]:
data["y"]=data["y"].map({"yes":1,"no":0})
data.head()

interest_rate  credit  march  may  previous  duration  y
0          1.334     0.0    1.0  0.0       0.0     117.0  0
1          0.767     0.0    0.0  2.0       1.0     274.0  1
2          4.858     0.0    1.0  0.0       0.0     167.0  0
3          4.120     0.0    0.0  0.0       0.0     686.0  1
4          4.856     0.0    1.0  0.0       0.0     157.0  0

In [11]:
data.describe(include='all')

interest_rate      credit       march         may    previous  \
count     518.000000  518.000000  518.000000  518.000000  518.000000   
mean        2.835776    0.034749    0.266409    0.388031    0.127413   
std         1.876903    0.183321    0.442508    0.814527    0.333758   
min         0.635000    0.000000    0.000000    0.000000    0.000000   
25%         1.042750    0.000000    0.000000    0.000000    0.000000   
50%         1.466000    0.000000    0.000000    0.000000    0.000000   
75%         4.956500    0.000000    1.000000    0.000000    0.000000   
max         4.970000    1.000000    1.000000    5.000000    1.000000   

          duration           y  
count   518.000000  518.000000  
mean    382.177606    0.500000  
std     344.295990    0.500483  
min       9.000000    0.000000  
25%     155.000000    0.000000  
50%     266.500000    0.500000  
75%     482.750000    1.000000  
max    2653.000000    1.000000

REGRESSION

In [12]:
x1=data["duration"]
y=data["y"]

In [13]:
x=sm.add_constant(x1)
reg=sm.Logit(y,x)
reg_logit=reg.fit()
reg_logit.summary()

Optimization terminated successfully.
         Current function value: 0.546118
         Iterations 7


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                      y   No. Observations:                  518
Model:                          Logit   Df Residuals:                      516
Method:                           MLE   Df Model:                            1
Date:                Mon, 19 Oct 2020   Pseudo R-squ.:                  0.2121
Time:                        21:32:53   Log-Likelihood:                -282.89
converged:                       True   LL-Null:                       -359.05
Covariance Type:            nonrobust   LLR p-value:                 5.387e-35
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.7001      0.192     -8.863      0.000      -2.076      -1.324
duration       0.0051      0.001      9.159      0.000       0.004       0.006
==============================================================================
"""

Considering all inputs

In [14]:
inputs=["interest_rate","credit","march","may","previous","duration"]
x2=data[inputs]
newy=data["y"]


In [15]:
x=sm.add_constant(x2)
reg1=sm.Logit(newy,x)
reg_Logit1=reg1.fit()
reg_Logit1.summary()

Optimization terminated successfully.
         Current function value: 0.335942
         Iterations 7


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                      y   No. Observations:                  518
Model:                          Logit   Df Residuals:                      511
Method:                           MLE   Df Model:                            6
Date:                Mon, 19 Oct 2020   Pseudo R-squ.:                  0.5153
Time:                        21:32:55   Log-Likelihood:                -174.02
converged:                       True   LL-Null:                       -359.05
Covariance Type:            nonrobust   LLR p-value:                 7.579e-77
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
const            -0.1385      0.339     -0.408      0.683      -0.804       0.527
interest_rate    -0.7802      0.092     -8.471      0.000      -0.961      -0.600
credit            2.4028      1.090      2.205      0.027       0.267       4.538
march            -1.8097      0.332     -5.459      0.000      -2.459      -1.160
may               0.1946      0.229      0.849      0.396      -0.255       0.644
previous          1.2746      0.583      2.186      0.029       0.132       2.417
duration          0.0070      0.001      9.386      0.000       0.006       0.008
=================================================================================
"""

Confusion Matrix

In [16]:
def confusion_matrix(data,actual_values,model):
    pred_values = model.predict(data)
    bins=np.array([0,0.5,1])
    cm = np.histogram2d(actual_values, pred_values, bins=bins)[0]
    accuracy = (cm[0,0]+cm[1,1])/cm.sum()
    return cm, accuracy

In [17]:
confusion_matrix(x,newy,reg_Logit1)

(array([[220.,  39.],
        [ 31., 228.]]),
 0.8648648648648649)

CONSIDERING THE TEST DATA FOR REGRESSION PROCESS

In [20]:
data2=pd.read_csv("C:\\Users\\anish\\Documents\\DATA_SCIENCE_JUPYTER\\Logistic Regression\\Bank-data-testing.csv")
data2

Unnamed: 0  interest_rate  credit  march  may  previous  duration    y
0             0          1.313     0.0    1.0  0.0       0.0     487.0   no
1             1          4.961     0.0    0.0  0.0       0.0     132.0   no
2             2          4.856     0.0    1.0  0.0       0.0      92.0   no
3             3          4.120     0.0    0.0  0.0       0.0    1468.0  yes
4             4          4.963     0.0    0.0  0.0       0.0      36.0   no
..          ...            ...     ...    ...  ...       ...       ...  ...
217         217          4.963     0.0    0.0  0.0       0.0     458.0  yes
218         218          1.264     0.0    1.0  1.0       0.0     397.0  yes
219         219          1.281     0.0    1.0  0.0       0.0      34.0   no
220         220          0.739     0.0    0.0  2.0       0.0     233.0   no
221         221          1.046     0.0    0.0  0.0       0.0     238.0  yes

[222 rows x 8 columns]

In [21]:
data2=data2.drop(["Unnamed: 0"],axis=1)
data2.head()

interest_rate  credit  march  may  previous  duration    y
0          1.313     0.0    1.0  0.0       0.0     487.0   no
1          4.961     0.0    0.0  0.0       0.0     132.0   no
2          4.856     0.0    1.0  0.0       0.0      92.0   no
3          4.120     0.0    0.0  0.0       0.0    1468.0  yes
4          4.963     0.0    0.0  0.0       0.0      36.0   no

In [22]:
data2["y"]=data2["y"].map({"yes":1,"no":0})
data2.head()

interest_rate  credit  march  may  previous  duration  y
0          1.313     0.0    1.0  0.0       0.0     487.0  0
1          4.961     0.0    0.0  0.0       0.0     132.0  0
2          4.856     0.0    1.0  0.0       0.0      92.0  0
3          4.120     0.0    0.0  0.0       0.0    1468.0  1
4          4.963     0.0    0.0  0.0       0.0      36.0  0

In [23]:
inputs=["interest_rate","credit","march","may","previous","duration"]
xtest=data2[inputs]
ytest=data2["y"]

In [28]:
x3=sm.add_constant(xtest)
x3

const  interest_rate  credit  march  may  previous  duration
0      1.0          1.313     0.0    1.0  0.0       0.0     487.0
1      1.0          4.961     0.0    0.0  0.0       0.0     132.0
2      1.0          4.856     0.0    1.0  0.0       0.0      92.0
3      1.0          4.120     0.0    0.0  0.0       0.0    1468.0
4      1.0          4.963     0.0    0.0  0.0       0.0      36.0
..     ...            ...     ...    ...  ...       ...       ...
217    1.0          4.963     0.0    0.0  0.0       0.0     458.0
218    1.0          1.264     0.0    1.0  1.0       0.0     397.0
219    1.0          1.281     0.0    1.0  0.0       0.0      34.0
220    1.0          0.739     0.0    0.0  2.0       0.0     233.0
221    1.0          1.046     0.0    0.0  0.0       0.0     238.0

[222 rows x 7 columns]

In [25]:
#TEST DATA_CONFUSION MATRIX
confusion_matrix(x3, ytest, reg_Logit1)

(array([[94., 17.],
        [12., 99.]]),
 0.8693693693693694)

In [26]:
#TRAIN DATA_CONFUSION MATRIX(PREVIOUS DATA)
confusion_matrix(x,newy,reg_Logit1)

(array([[220.,  39.],
        [ 31., 228.]]),
 0.8648648648648649)

Therefore, test accuracy > train accuracy 